version: "3.8"

services:
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   hostname: redis
  #   volumes:
  #     - "./data/redis:/data"
  #   expose:
  #     - 6379
  llama3:
    # container_name: llama3
    build: .
    environment:
      - MODEL_DIR=/data/models
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AIXBLOCK_USE_REDIS=false
    ports:
      - 9090:9090
    # depends_on:
    #   - redis
    # links:
    #   - redis
    volumes:
      - "./data/server:/data"
      - "./logs:/tmp"
